[project]
name = "langchain-course"
version = "0.1.0"
description = ""
authors = [
    {name = "Rishikesh Sahoo",email = "rishikeshsahoo2828@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0.0"
dependencies = [
    "langchain (>=1.1.0,<2.0.0)",
    "langchain-tavily (>=0.2.13,<0.3.0)",
    "python-dotenv (>=1.2.1,<2.0.0)",
    "tavily-python (>=0.7.13,<0.8.0)",
    "langchain-google-genai (>=3.2.0,<4.0.0)",
    "grandalf (>=0.8,<0.9)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
